cc_library(
    name = "foobar",
    srcs = ["src/foobar.cpp"],
    hdrs = ["inc/foobar/foobar.h"],
    includes = ["inc"],
    deps = ["@spdlog//:spdlog"],
    visibility = ["//visibility:public"],
) 